#provide tag and path to FASTA, chromosome sizes file, and annotation for heatmaps
combinedgenome :
    name : ScSp
    fasta : ../genome/ScSp.R64.2-1.ASM294v2.fa
    gff : ../genome/ScSp.R64.2-1.ASM294v2.gff
    chrsizes : ../genome/ScSp.R64.2-1.ASM294v2.chrsizes.tsv
    experimental_prefix : "Scer_"
    spikein_prefix : "Spom_"

genome:
    fasta : ../genome/S_cerevisiae.R64-2-1.fa
    chrsizes : ../genome/S_cerevisiae.R64-2-1.chrsizes.tsv
    si-chrsizes: ../genome/S_pombe.ASM294v2.chrsizes.tsv
    orf-annotation: ../genome/annotations/Scer_nondubious_ORFs.bed
    transcripts: ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed

factor: "tfiib" #name of the factor being ChIP'ed (for file-naming purposes only)

samples:
    diamide-1:
        fastq : fastq/Dia_1_TTAGGC.R1.fastq.gz
        group : "diamide"
        pass-qc : pass
        spikein : y
    diamide-2:
        fastq : fastq/Dia_2_TGACCA.R1.fastq.gz
        group : "diamide"
        pass-qc : pass
        spikein : y
    nitrogen-1:
        fastq : fastq/Nit_1_CTGATC.R1.fastq.gz
        group : "nitrogen"
        pass-qc : pass
        spikein : y
    nitrogen-2:
        fastq : fastq/Nit_2_AAGCTA.R1.fastq.gz
        group : "nitrogen"
        pass-qc : pass
        spikein : y
    SC-1:
        fastq : fastq/SC_A_ACAGTG.R1.fastq.gz
        group : "SC"
        pass-qc : pass
        spikein : y
    SC-2:
        fastq : fastq/SC_B_GCCAAT.R1.fastq.gz
        group : "SC"
        pass-qc : pass
        spikein : y
    SD-1:
        fastq : fastq/SD_A_CAGATC.R1.fastq.gz
        group : "SD"
        pass-qc : pass
        spikein : y
    SD-2:
        fastq : fastq/SD_B_ACTTGA.R1.fastq.gz
        group : "SD"
        pass-qc : pass
        spikein : y
    spt6-37-1:
        fastq : fastq/spt6A_S3_L001_R1_001.fastq.gz
        group : "spt6-37"
        pass-qc : pass
        spikein : y
    spt6-37-2:
        fastq : fastq/spt6B_S4_L001_R1_001.fastq.gz
        group : "spt6-37"
        pass-qc : pass
        spikein : y
    WT-37-1:
        fastq : fastq/WTA_S1_L001_R1_001.fastq.gz
        group : "WT-37"
        pass-qc : pass
        spikein : y
    WT-37-2:
        fastq : fastq/WTB_S2_L001_R1_001.fastq.gz
        group : "WT-37"
        pass-qc : pass
        spikein : y
    YPD-1:
        fastq : fastq/YPD30_1_ATCACG.R1.fastq.gz
        group : "YPD"
        pass-qc : pass
        spikein : y
    YPD-2:
        fastq : fastq/YPD30_2_CGATGT.R1.fastq.gz
        group : "YPD"
        pass-qc : pass
        spikein : y

#The following lists are ordered, i.e. the first condition is matched with the first control, etc. Therefore, the lists must be the same length, and the values of the conditions and controls must be present in the above sample list
comparisons:
    libsizenorm :
        conditions:
            - "diamide"
            - "spt6-37"
            - "nitrogen"
            - "SD"
        controls:
            - "YPD"
            - "WT-37"
            - "SC"
            - "SC"
    spikenorm:
        conditions:
            - "diamide"
            - "spt6-37"
            - "nitrogen"
            - "SD"
        controls:
            - "YPD"
            - "WT-37"
            - "SC"
            - "SC"

cutadapt:
    #trim_qual : 25
    adapter: "AGATCGGAAGAGCACAC"

bowtie2:
    minmapq : 5

corr-windowsize: 100

threads: 2

annotations:
    allPolII-TSS:
        path : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
        binsize : 10 
        binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
        refpoint : "TSS" # OPTIONS: TSS, TES , center
        upstream : 500
        dnstream : 4000
        sort : "ascend" # OPTIONS: descend, ascend, no, keep
        sortby : "region_length"
        pct_cutoff : .98 # do not plot data above this percentile in heatmaps
        heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
        refpointlabel : "TSS" # label for reference point
        ylabel : "coding genes"      # y-axis label (for regions represented in the BED file)
    allPolII-TSSzoom:
        path : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
        binsize : 1
        binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
        refpoint : "TSS" # OPTIONS: TSS, TES , center
        upstream : 300
        dnstream : 100
        sort : "ascend" # OPTIONS: descend, ascend, no, keep
        sortby : "region_length"
        pct_cutoff : 1 # do not plot data above this percentile in heatmaps
        heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
        refpointlabel : "TSS" # label for reference point
        ylabel : "coding genes"      # y-axis label (for regions represented in the BED file)

# #minimum reads PER SAMPLE for prefiltering
# minreads: 2

# deseq:
#     fdr : 0.1
#     fold-change-threshold: 1

# cluster-merge-distance: 10

# #distance upstream of TSS in transcript annotation file to still be considered as genic when classifying peaks
# genic-windowsize: 30
# max-convergent-dist: 500
# max-divergent-dist: 500

# max-upstr-atgs: 3 #maximum number of ATGs between intragenic start and ATG of potential intragenic ORF to output that intragenic ORF

# meme-chip:
#     motif-database : ../genome/motifs/YEASTRACT_20130918.meme 
#     upstream-dist: 50      #distance upstream of peaks to search for motifs
#     downstream-dist: 50    #distance downstream of peaks to search for motifs
#     max-frag-size: 100     #meme-chip -ccut
#     meme-mode : "anr"      #meme mode: oops|zoops|anr
#     meme-nmotifs : 10      #meme max number of motifs to find
#     #meme-maxsize : 



