#provide tag and path to FASTA, chromosome sizes file 
combinedgenome :
    name : ScSp
    fasta : ../genome/ScSp.R64.2-1.ASM294v2.fa
    gff : ../genome/ScSp.R64.2-1.ASM294v2.gff
    chrsizes : ../genome/ScSp.R64.2-1.ASM294v2.chrsizes.tsv
    experimental_prefix : "Scer_"
    spikein_prefix : "Spom_"

genome:
    fasta : ../genome/S_cerevisiae.R64-2-1.fa
    chrsizes : ../genome/S_cerevisiae.R64-2-1.chrsizes.tsv
    si-chrsizes: ../genome/S_pombe.ASM294v2.chrsizes.tsv
    orf-annotation: ../genome/annotations/Scer_nondubious_ORFs.bed
    transcripts: ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed

factor: "tfiib" #name of the factor being ChIP'ed (for file-naming purposes only)

samples:
    YPD-1:
        fastq : fastq/YPD30_1_ATCACG.R1.fastq.gz
        group : "YPD"
        pass-qc : pass
        spikein : y
    YPD-2:
        fastq : fastq/YPD30_2_CGATGT.R1.fastq.gz
        group : "YPD"
        pass-qc : pass
        spikein : y
    diamide-1:
        fastq : fastq/Dia_1_TTAGGC.R1.fastq.gz
        group : "diamide"
        pass-qc : pass
        spikein : y
    diamide-2:
        fastq : fastq/Dia_2_TGACCA.R1.fastq.gz
        group : "diamide"
        pass-qc : pass
        spikein : y
    SC-1:
        fastq : fastq/SC_A_ACAGTG.R1.fastq.gz
        group : "SC"
        pass-qc : pass
        spikein : y
    SC-2:
        fastq : fastq/SC_B_GCCAAT.R1.fastq.gz
        group : "SC"
        pass-qc : pass
        spikein : y
    nitrogen-1:
        fastq : fastq/Nit_1_CTGATC.R1.fastq.gz
        group : "nitrogen"
        pass-qc : pass
        spikein : y
    nitrogen-2:
        fastq : fastq/Nit_2_AAGCTA.R1.fastq.gz
        group : "nitrogen"
        pass-qc : pass
        spikein : y
    SD-1:
        fastq : fastq/SD_A_CAGATC.R1.fastq.gz
        group : "SD"
        pass-qc : pass
        spikein : y
    SD-2:
        fastq : fastq/SD_B_ACTTGA.R1.fastq.gz
        group : "SD"
        pass-qc : pass
        spikein : y
    WT-37-1:
        fastq : fastq/WTA_S1_L001_R1_001.fastq.gz
        group : "WT-37"
        pass-qc : pass
        spikein : y
    WT-37-2:
        fastq : fastq/WTB_S2_L001_R1_001.fastq.gz
        group : "WT-37"
        pass-qc : pass
        spikein : y
    spt6-37-1:
        fastq : fastq/spt6A_S3_L001_R1_001.fastq.gz
        group : "spt6-37"
        pass-qc : pass
        spikein : y
    spt6-37-2:
        fastq : fastq/spt6B_S4_L001_R1_001.fastq.gz
        group : "spt6-37"
        pass-qc : pass
        spikein : y
   
#The following lists are ordered, i.e. the first condition is matched with the first control, etc. Therefore, the lists must be the same length, and the values of the conditions and controls must be present in the above sample list
comparisons:
    libsizenorm :
        conditions:
            - "diamide"
            - "nitrogen"
            - "SD"
            - "spt6-37"
        controls:
            - "YPD"
            - "SC"
            - "SC"
            - "WT-37"
    spikenorm:
        conditions:
            - "diamide"
            - "nitrogen"
            - "SD"
            - "spt6-37"
        controls:
            - "YPD"
            - "SC"
            - "SC"
            - "WT-37"

cutadapt:
    #trim_qual : 25
    adapter: "AGATCGGAAGAGCACAC"

bowtie2:
    minmapq : 5

macs2:
    bw: 160 #bandwidth for model building: set as sonication fragment size
    slocal: 200 #small region for calculating local lambda
    llocal: 1000 #large region for calculating local lambda
    fdr: 0.01 #minimum cutoff to call significant regions

corr-windowsize: 10

threads: 2

annotations:
    # allPolII-TSS:
    #     path : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
    #     binsize : 10 
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 500
    #     dnstream : 4000
    #     nan_afterend : y
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .98 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TSS" # label for reference point
    #     ylabel : "coding genes"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 5.5 #width PER GROUP in cm
    # verified-transcripts:
    #     path : ../genome/annotations/Scer_transcripts_w_verifiedORFs.bed
    #     binsize : 10 
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 500
    #     dnstream : 3000
    #     nan_afterend : y
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .95 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "viridis"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TSS" # label for reference point
    #     ylabel : "coding genes"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 5.5 #width PER GROUP in cm
    diamide-up-TSS:
        path : ../tss-seq/diff_exp/diamide-v-YPD/diamide-v-YPD-results-spikenorm-up.bed
        binsize : 10 
        binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
        refpoint : "center" # OPTIONS: TSS, TES , center
        upstream : 300
        dnstream : 100 
        nan_afterend : n
        sort : "keep" # OPTIONS: descend, ascend, no, keep
        sortby : "region_length"
        pct_cutoff : .95 # do not plot data above this percentile in heatmaps
        cluster : TRUE #TRUE:cluster with k-means, FALSE: do not cluster
        nclusters : 5
        heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
        refpointlabel : "TSS" # label for reference point
        ylabel : "diamide-induced TSSs"      # y-axis label (for regions represented in the BED file)
        figwidth: 5.5 #width PER GROUP in cm
    spt6-up-TSS:
        path : ../tss-seq/diff_exp/spt6-37-v-WT-37/spt6-37-v-WT-37-results-spikenorm-up.bed
        binsize : 10 
        binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
        refpoint : "center" # OPTIONS: TSS, TES , center
        upstream : 300
        dnstream : 100 
        nan_afterend : n
        sort : "keep" # OPTIONS: descend, ascend, no, keep
        sortby : "region_length"
        pct_cutoff : .95 # do not plot data above this percentile in heatmaps
        cluster : TRUE #TRUE:cluster with k-means, FALSE: do not cluster
        nclusters : 5
        heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
        refpointlabel : "TSS" # label for reference point
        ylabel : "spt6-1004 induced TSSs"      # y-axis label (for regions represented in the BED file)
        figwidth: 5.5 #width PER GROUP in cm

    # divergent-pairs:
    #     path : ../genome/annotations/Scer_divergent-gene-pairs.bed
    #     binsize : 10 
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TES" # OPTIONS: TSS, TES , center
    #     upstream : 2500
    #     dnstream : 0
    #     sort : "keep" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .98 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TSS" # label for reference point
    #     ylabel : "divergent gene pairs"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 5.5 #width PER GROUP in cm
    # allPolII-TSSzoom:
    #     path : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
    #     binsize : 1
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 300
    #     dnstream : 100
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .97 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TSS" # label for reference point
    #     ylabel : "coding genes"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 4.5 #width PER GROUP in cm
    # rhee2012raw:
    #     path : ../genome/annotations/rhee2012_tata-roman-slopR120.bed
    #     binsize : 1
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 30
    #     dnstream : 120
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .97 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TATA" # label for reference point
    #     ylabel : "TATA boxes (directly from Rhee 2012)"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 4.5 #width PER GROUP in cm
    # rhee2012inclwrongstrand:
    #     path : ../genome/annotations/rhee2012_inclwrongstrand-slopR120.bed
    #     binsize : 1
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 30
    #     dnstream : 120
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .97 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
        # refpointlabel : "TATA" # label for reference point
        # ylabel : "TATA boxes (from Rhee 2012, checked for TATA)"      # y-axis label (for regions represented in the BED file)
        # figwidth: 4.5 #width PER GROUP in cm
    # rhee2012cleaned:
    #     path : ../genome/annotations/rhee2012_cleaned-slopR120.bed
    #     binsize : 1
    #     binstat : "mean" # OPTIONS: mean, median, min, max, sum, std
    #     refpoint : "TSS" # OPTIONS: TSS, TES , center
    #     upstream : 30
    #     dnstream : 120
    #     sort : "ascend" # OPTIONS: descend, ascend, no, keep
    #     sortby : "region_length"
    #     pct_cutoff : .97 # do not plot data above this percentile in heatmaps
    #     heatmap_colormap : "inferno"  # OPTIONS: viridis, inferno, magma, plasma
    #     refpointlabel : "TATA" # label for reference point
    #     ylabel : "TATA boxes (from Rhee 2012, checked for TATA on correct strand)"      # y-axis label (for regions represented in the BED file)
    #     figwidth: 4.5 #width PER GROUP in cm
    
# #minimum reads PER SAMPLE for prefiltering
# minreads: 2

deseq:
    fdr : 0.1
    fold-change-threshold: 2

# cluster-merge-distance: 10

# #distance upstream of TSS in transcript annotation file to still be considered as genic when classifying peaks
genic-windowsize: 30
# max-convergent-dist: 500
# max-divergent-dist: 500

# max-upstr-atgs: 3 #maximum number of ATGs between intragenic start and ATG of potential intragenic ORF to output that intragenic ORF

# meme-chip:
#     motif-database : ../genome/motifs/YEASTRACT_20130918.meme 
#     upstream-dist: 50      #distance upstream of peaks to search for motifs
#     downstream-dist: 50    #distance downstream of peaks to search for motifs
#     max-frag-size: 100     #meme-chip -ccut
#     meme-mode : "anr"      #meme mode: oops|zoops|anr
#     meme-nmotifs : 10      #meme max number of motifs to find
#     #meme-maxsize : 



